---
name: checks

on: [push]

jobs:
    test-lint:
        name: Test and Lint
        runs-on: ubuntu-20.04
        steps:git pus
            - name: Login to Docker hub
              uses: docker/login-action@v2
              with:
                username: ${{ secrets.DOCKER_USERNAME }}
                password: ${{ secrets.DOCKERHUB_TOKEN }}
            - name: Checkout
              uses: actions/checkout@v2
            - name: Tests
              run: docker-compose run --rm backnd python manage.py test 
            - name: Lint
              run: docker-compose run --rm backnd flake8
