name: Docker Build and Test

on:
  push:
    branches:
      - main  
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Install Docker Compose
        run: |
          DOCKER_COMPOSE_VERSION=$(curl -s https://api.github.com/repos/docker/compose/releases/latest | jq -r .tag_name)
          sudo curl -L "https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose

      - name: Check Docker Compose version
        run: |
          docker-compose --version 

      - name: Build and run Docker Compose
        run: |
          docker-compose up -d  
          docker-compose ps     

      - name: Run tests
        run: |
          docker-compose run --rm backnd python manage.py test  

      - name: Print environment variables
        run: env

      - name: List installed packages
        run: |
          docker --version
          docker compose version